includes:
  - "/home/claireh/running-ng/config/base/minheap.yml"

benchmarks:
  dacapochopin-f480064:
    - jython

overrides:
  "suites.dacapochopin-f480064.timing_iteration": 5
  "suites.dacapochopin-f480064.callback": "probe.DacapoChopinCallback"
  "suites.dacapochopin-f480064.timeout": 600

runtimes:
# BarrierSelector set to ObjectBarrier
  bar:
    type: OpenJDK
    release: 11
    home: "/home/claireh/running-ng/builds/build_barrier/linux-x86_64-normal-server-release/jdk"
# BarrierSelector set to ObjectBarrier
  no-bar:
    type: OpenJDK
    release: 11
    home: "/home/claireh/running-ng/builds/build_no_barrier/linux-x86_64-normal-server-release/jdk"

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/claireh/probes /home/claireh/probes/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/claireh/probes -Dprobes=RustMMTk"

configs:
  - "bar|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes"
  - "no-bar|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes"





